apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluid-workload.fullname" . }}-config
  labels:
    {{- include "fluid-workload.labels" . | nindent 4 }}
data:
{{- $files := fromYaml (include "fluid-workload.configFiles" .) }}
{{- range $name, $content := $files }}
  {{ $name }}: |
{{ $content | nindent 4 }}
{{- end }}
