apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluid-workload.fullname" . }}-config
  labels:
    {{- include "fluid-workload.labels" . | nindent 4 }}
data:
  {{ .Values.configMount.fileName }}: |
{{ .Values.config.content | nindent 4 }}
